apiVersion: v1
kind: Service
metadata:
  name: FanzProtect
  labels:
    app: FanzProtect
    system: fanz
spec:
  selector:
    app: FanzProtect
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
